---
title: "p8105_hw2_ly2496"
author: "Ling Yi"
date: "9/23/2020"
output: github_document
---

Problem 0

##loading the packages needed

```{r}
library(tidyverse)
library(readxl)
```


?read_excel

##problem 1

```{r}
trashwheel_df =
  read_excel("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
             sheet = "Mr. Trash Wheel",
             range = cell_cols("A:N")) %>%
            janitor:: clean_names() %>%
            drop_na(dumpster)%>%
          mutate(
              sports_balls=round(sports_balls),
              sports_balls = as.integer(sports_balls)
          )
```

##read in precipitation data

```{r}
precip_2018 =
  read_excel ("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
              sheet = "2018 Precipitation",
              skip = 1) %>% 
              janitor:: clean_names() %>%
              drop_na(month) %>% 
  mutate(year = 2018) %>% 
  relocate(year)
```

```{r}
precip_2017 =
  read_excel ("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
              sheet = "2017 Precipitation",
              skip = 1) %>% 
              janitor:: clean_names() %>%
              drop_na(month) %>% 
  mutate(year = 2017) %>% 
  relocate(year)
```


```{r}
month_df=
  tibble(
    month =  1:12,
    month_name=month.name
  )

precip_df = 
  bind_rows(precip_2018, precip_2017) %>%  view


left_join(precip_df, month_df, by = "month")

```

